server:
  port: 8081
spring:
  #文件上传大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  #数据源
  datasource:
    username: root
    password: Aa3692581470;
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.229.14:3306/professional_website?characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    #配置静态资源的路径
    static-path-pattern: /resources/**
    view:
      #配置访问页面的前缀
      prefix: /html/
      #配置访问页面的后缀
      suffix: .html
      resources:
        static-locations: /resources/
    favicon:
      enabled: false
#整合mybatis
mybatis:
  type-aliases-package: com.turing.turing.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql
teacher:
  ImgPath: D:\upload\img\
  requestImgPath: file:D:\upload\img\
pdfPath: D:\upload\pdf\
requestPdfPath: file:D:\upload\pdf\
team:
  ImgPath: D:\upload\team\
  requestImgPath: file:D:\upload\team\
course:
  requestPPTPath: file:D:\upload\ppt\
#打印sql语句
logging:
  level:
    com.turing.professional_website.dao : debug

