server:
  port: 8082
spring:
  datasource:
    username: root
    password: Meng&Zeng_1120&1202_professional_website
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://210.38.139.201:3306/professional_website?characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /html/
      suffix: .html
    favicon:
      enabled: false
    resources:
      static-locations: /resources/
mybatis:
  type-aliases-package: com.turing.turing.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql